name: Build and publish installers
on:
  push:
    tags:
      - v*
jobs:
  build-and-publish:
    name: Build and publish installers
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            suffix: Linux-x86_64.sh
          - os: macos-latest
            suffix: MacOSX-x86_64.pkg
          - os: windows-latest
            suffix: Windows-x86_64.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract version
        id: meta
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
      - name: Install constructor
        shell: bash -el {0}
        run: conda install -c conda-forge -y constructor
      - name: Build installers
        shell: bash -el {0}
        run: constructor
      - name: Publish installers
        uses: actions/upload-artifact@v4
        with:
          name: Birka-${{ steps.meta.outputs.version }}-${{ matrix.suffix }}
          path: Birka-${{ steps.meta.outputs.version }}-${{ matrix.suffix }}
